export const API_URL = 'http://localhost:3000';
export const TIMEOUT_SEC = 10;
export const MODAL_CLOSE_SEC = 2.5;
export const FUSE_OPTIONS = {
  isCaseSensitive: false,
  includeScore: true,
  shouldSort: true,
  threshold: 0.3,
  keys: [
    'email',
    'prenom',
    'nom',
    'role',
    'structure',
    'date_naissance',
    'active',
  ],
};

export const GROUP_DEFINITIONS = {
  Utilisateur: [
    'register',
    'show users',
    'show user',
    'update user',
    'delete user',
    'change status',
    'change password auth',
    'rattacher',
  ],
  Chapitres: ['add chapter', 'delete chapter', 'update chapter'],
  Produits_et_Articles: [
    'add product',
    'delete product',
    'show products',
    'show articles',
    'add article',
    'update article',
    'delete article',
    'add fournisseur',
    'delete fournisseur',
    'show fournisseurs',
  ],
  Commandes: [
    'show chapters',
    'bon commande',
    'delete commande',
    'update quantite',
    'cancel commande',
    'show commandes',
    'update bon commande',
    'update fournisseur',
    'update raison sociale',
  ],
  Roles_et_Permissions: [
    'add role',
    'show roles',
    'delete role',
    'show permissions',
    'add permissions',
    'delete permissions',
  ],
  Structure: [
    'update structure',
    'delete structure',
    'add structure',
    'show structure',
  ],
};
export const PERM_NAMES = {
  register: 'Enregistrer',
  'show users': 'Afficher les utilisateurs',
  'show user': "Afficher l'utilisateur",
  'update user': "Mettre à jour l'utilisateur",
  'delete user': "Supprimer l'utilisateur",
  'change status': 'Changer le statut',
  'change password auth': "Modifier le mot de passe d'authentification",
  rattacher: 'Raattacher',
  'add chapter': 'Ajouter un chapitre',
  'delete chapter': 'Supprimer le chapitre',
  'update chapter': 'Mettre à jour le chapitre',
  'add product': 'Ajouter un produit',
  'delete product': 'Supprimer le produit',
  'show products': 'Afficher les produits',
  'show articles': 'Afficher les articles',
  'add article': 'Ajouter un article',
  'update article': "Mettre à jour l'article",
  'delete article': "Supprimer l'article",
  'add fournisseur': 'Ajouter un fournisseur',
  'delete fournisseur': 'Supprimer le fournisseur',
  'show fournisseurs': 'Afficher les fournisseurs',
  'show chapters': 'Afficher les chapitres',
  'bon commande': 'Bon de commande',
  'delete commande': 'Supprimer la commande',
  'update quantite': 'Mettre à jour la quantité',
  'cancel commande': 'Annuler la commande',
  'show commandes': 'Afficher les commandes',
  'update bon commande': 'Mettre à jour le bon de commande',
  'update fournisseur': 'Mettre à jour le fournisseur',
  'update raison sociale': 'Mettre à jour la raison sociale',
  'add role': 'Ajouter un rôle',
  'show roles': 'Afficher les rôles',
  'delete role': 'Supprimer le rôle',
  'show permissions': 'Afficher les permissions',
  'add permissions': 'Ajouter des permissions',
  'delete permissions': 'Supprimer des permissions',
  'update structure': 'Mettre à jour la structure',
  'delete structure': 'Supprimer la structure',
  'add structure': 'Ajouter une structure',
  'show structure': 'Afficher la structure',
};
